# Generated by Django 4.2.13 on 2024-07-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=255)),
                ('mobile_format_id', models.IntegerField()),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency')),
            ],
        ),
    ]
