# Generated by Django 4.2.13 on 2024-06-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='extenduser',
            name='last_name',
        ),
    ]
