# Generated by Django 4.2.13 on 2024-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=5)),
                ('country_code', models.CharField(max_length=5)),
            ],
        ),
    ]
