# Generated by Django 4.2.13 on 2024-07-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDetail',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_status', models.CharField(max_length=10)),
                ('branch_type', models.CharField(max_length=10)),
                ('work_type', models.IntegerField()),
                ('cash_drawer', models.CharField(choices=[('M', 'Main'), ('S', 'Sub')], max_length=1)),
                ('zone_id', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companydetail')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contactdetail')),
            ],
        ),
    ]
