# Generated by Django 4.2.13 on 2024-07-11 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_mobile', models.BigIntegerField()),
                ('international_calling_code', models.IntegerField()),
                ('calling_country', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_pin', models.CharField(max_length=255)),
                ('fcm_key', models.TextField()),
                ('isPinResetRequested', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
