# Generated by Django 4.2.13 on 2024-07-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='fcm_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
