# Generated by Django 4.2.13 on 2024-07-24 21:33

import companies.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_business_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_gstin', models.CharField(max_length=255, validators=[companies.models.validate_gst_number])),
                ('company_status', models.CharField(max_length=10)),
                ('company_dawn', models.TimeField()),
                ('company_dusk', models.TimeField()),
                ('company_timeslice', models.TimeField()),
                ('FSSAI', models.CharField(max_length=255)),
                ('aadhar_number', models.CharField(max_length=14, validators=[companies.models.validate_aadhar_number])),
                ('pan', models.CharField(max_length=10, validators=[companies.models.validate_pan_number])),
                ('company_address', models.TextField()),
                ('business_type', models.CharField(max_length=255)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_feature_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companydetail')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.appfeatures')),
            ],
        ),
    ]
