# Generated by Django 4.2.13 on 2024-07-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo_path', models.CharField(max_length=255)),
                ('company_business_id', models.IntegerField()),
                ('company_revenue_id', models.IntegerField()),
                ('company_website', models.URLField()),
                ('company_gstin', models.CharField(max_length=255)),
                ('company_status', models.CharField(max_length=1)),
                ('feedback_flag', models.CharField(max_length=1)),
                ('company_dawn', models.TimeField()),
                ('company_dusk', models.TimeField()),
                ('company_timeslice', models.TimeField()),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=255)),
                ('merchant_id', models.TextField()),
                ('merchant_secret_key', models.TextField()),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('radius', models.CharField(max_length=255)),
                ('customer_app', models.CharField(max_length=1)),
                ('appointment_auto_confirm', models.BooleanField()),
                ('FSSAI', models.CharField(max_length=255)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_feature_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companydetail')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.appfeatures')),
            ],
        ),
    ]
