# Generated by Django 4.2.13 on 2024-07-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='company_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='feedback_flag',
            field=models.CharField(max_length=10),
        ),
    ]
