# Generated by Django 4.2.13 on 2024-07-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companydetail_company_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='customer_app',
            field=models.CharField(max_length=10),
        ),
    ]
